server {
    listen 80; # Đưa web về cổng 80 chuẩn

    # 1. Phục vụ giao diện React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}