version: '3.8'

services:
  # Khai báo service Product của Hoàn
  product-service:
    build: .
    container_name: hoan_product_service
    ports:
      - "8001:8001" # Ánh xạ port 8001 của máy tính vào port 8001 của container
    environment:
      - PORT=8001
      # Truyền link MongoDB Cloud chung của nhóm vào đây
      - MONGO_URI=mongodb+srv://bmbtrung_db_user:ZYcO5VqRTkob3v1c@soa.fvwonfx.mongodb.net/product_db?appName=SOA
    networks:
      - doan_network

# Cấu hình network nội bộ (sau này Tú làm Order Service cũng sẽ join vào chung network này)
networks:
  doan_network:
    driver: bridge